# Generated by Django 4.1.4 on 2023-01-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_remove_status_name_status_como'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='status',
        ),
        migrations.AddField(
            model_name='todolist',
            name='como',
            field=models.CharField(choices=[('FA', '⛔️ a Fazer'), ('RE', '⚠️ Fazendo'), ('FI', '✅ Finalizado')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
